version: 0.0
os: linux
files:
  - source: /airflow_plugin/
    destination: /home/airflow/airflow/code_deploy/plugins/
    overwrite: true
  - source: /dags/
    destination: /home/airflow/airflow/code_deploy/dags/
    overwrite: true
  - source: /apps/pipeline/
    destination: /home/airflow/airflow/code_deploy/apps/
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:    
  AfterInstall:
    - location: code_deploy_copy_files.sh
      timeout: 300