version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 721495903582.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t data-pipeline:data_ingestion -f apps/pipeline/pipeline.docker .
      - docker tag data-pipeline:data_ingestion 721495903582.dkr.ecr.ap-southeast-2.amazonaws.com/data-pipeline:data_ingestion      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 721495903582.dkr.ecr.ap-southeast-2.amazonaws.com/data-pipeline:data_ingestion